### ISSUE TITLE
feedback/issues

### ISSUE THREAD

**Issue by samdarwin** [wanelo-chef/ohai-private-ipaddress#2]
1. metadata.json should include:
name             'ohai-private-ipaddress'

2. README.md could say:
" The value will be available in a recipe as x = node['private_ipaddress'] "

3. chef supermarket doesn't have latest version.

**Comment by samdarwin** [comment]
4.  private-ipaddress.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html

**Comment by sax** [comment]
To be honest, we don't even use this anymore. We realized that if we drop in the ipaddr_extensions gem, ohai will automatically add `privateaddress` to the automatic attributes.

**Comment by minjar-jaiprakash** [comment]
Can you please give me some more explanation on ipaddr_extensions gem file...where I need to add it exactly in my cookbook so I can retrieve private ip addresses? It would be a great help for our project.

**Comment by sax** [comment]
I have the following cookbook, which uses a library file to install the `ipaddr_extensions` gem during chef convergence (before node automatic attributes are fully loaded). https://github.com/livinginthepast/ipaddr_extensions

If you include this cookbook, you will then be able to access `node['privateaddress']`.

If you run into any issues, please file a ticket there... I've run into problems before with different versions of rubygems.
